/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import com.controller.configuracionController;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MiguelCastellanos
 */
public class Config extends javax.swing.JFrame {

    /**
     * Creates new form Config
     */
    
    configuracionController cf = new configuracionController();
    
    public Config() {
        initComponents();
        cf.leerArchivo();
        txttienda.setText(System.getProperty("tienda"));
        //txtusuario.setVisible(false);
        txtencargado.setText(System.getProperty("encargado"));
        //txtpass.setVisible(false);
        nmayoreo.setValue(Integer.valueOf(System.getProperty("ncortemayoreo")));
        nmenudeo.setValue(Integer.valueOf(System.getProperty("ncortemenudeo")));
        nauxiliar.setValue(Integer.valueOf(System.getProperty("ncorteauxiliar")));
        nboucher.setValue(Integer.valueOf(System.getProperty("numboucher")));
        //numz.setValue(Integer.valueOf(System.getProperty("numz")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txttienda = new javax.swing.JTextField();
        txtencargado = new javax.swing.JTextField();
        nmenudeo = new javax.swing.JSpinner();
        nboucher = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nmayoreo = new javax.swing.JSpinner();
        nauxiliar = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        numz = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(6, 18, 32));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONFIGURACIÓN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 15, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TIENDA: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 61, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ENCARGADO:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 105, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("N. CORTE MENUDEO:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 189, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("N. BOUCHER:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 271, -1, -1));

        txttienda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txttienda.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txttienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 58, 294, -1));

        txtencargado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtencargado.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtencargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 102, 294, -1));

        nmenudeo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(nmenudeo, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 189, 118, -1));

        nboucher.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(nboucher, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 271, 118, -1));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Guardar");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 365, 76, 28));

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Salir");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 365, 72, 28));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("N. CORTE MAYOREO:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 146, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("N. CORTE AUXILIAR:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 230, -1, -1));

        nmayoreo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(nmayoreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 146, 118, -1));

        nauxiliar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(nauxiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 230, 118, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("N. Z");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 312, -1, -1));

        numz.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(numz, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 312, 117, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            cf.modificarArchivo((int) nmenudeo.getValue(),(int) nmayoreo.getValue(),(int) nauxiliar.getValue() , txttienda.getText(), txtencargado.getText(), (int) nboucher.getValue());
            JOptionPane.showMessageDialog(rootPane, "Guardado");
            this.setVisible(false);
        } catch (IOException ex) {
            //Logger.getLogger(Config.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Config().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner nauxiliar;
    private javax.swing.JSpinner nboucher;
    private javax.swing.JSpinner nmayoreo;
    private javax.swing.JSpinner nmenudeo;
    private javax.swing.JSpinner numz;
    private javax.swing.JTextField txtencargado;
    private javax.swing.JTextField txttienda;
    // End of variables declaration//GEN-END:variables
}
