
package com.view;

import com.controller.configuracionController;
import com.controller.reporteController;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.Calendar;
import java.util.Currency;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Copper
 */
public class Home extends javax.swing.JFrame {

    reporteController provedor = new reporteController();
    configuracionController cc = new configuracionController(); 
    /**
     * Creates new form Home
     */
    
    String op;
    String users;
    public Home() throws SQLException {
        initComponents();
        op = JOptionPane.showInputDialog(rootPane, "Eliga un usuario: \n 4.-MAYOREO \n 2.-MENUDEO" );
        getProvedores();
        getUsuario();
    }   

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("com/resources/reporte.png"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        btnconfiguracion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jfecha = new com.toedter.calendar.JDateChooser();
        jLabel28 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        L1 = new javax.swing.JSpinner();
        L2 = new javax.swing.JSpinner();
        L3 = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        monedas = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        cheques = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        subtotalL = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        boucher = new javax.swing.JSpinner();
        l1comentario = new javax.swing.JTextField();
        l2comentario = new javax.swing.JTextField();
        l3comentario = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jprovedor1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtprovedor1 = new javax.swing.JTextField();
        jprovedor2 = new javax.swing.JComboBox<>();
        jprovedor3 = new javax.swing.JComboBox<>();
        jprovedor4 = new javax.swing.JComboBox<>();
        jprovedor5 = new javax.swing.JComboBox<>();
        jprovedor6 = new javax.swing.JComboBox<>();
        txtprovedor2 = new javax.swing.JTextField();
        txtprovedor3 = new javax.swing.JTextField();
        txtprovedor4 = new javax.swing.JTextField();
        txtprovedor5 = new javax.swing.JTextField();
        txtprovedor6 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        subtotalcompras = new javax.swing.JLabel();
        por1 = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        por2 = new javax.swing.JSpinner();
        por3 = new javax.swing.JSpinner();
        por4 = new javax.swing.JSpinner();
        por5 = new javax.swing.JSpinner();
        por6 = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtgasto1 = new javax.swing.JTextField();
        txtgasto2 = new javax.swing.JTextField();
        txtgasto3 = new javax.swing.JTextField();
        txtgasto4 = new javax.swing.JTextField();
        txtgasto5 = new javax.swing.JTextField();
        txtgasto6 = new javax.swing.JTextField();
        txtgasto7 = new javax.swing.JTextField();
        gasto1 = new javax.swing.JSpinner();
        gasto2 = new javax.swing.JSpinner();
        gasto3 = new javax.swing.JSpinner();
        gasto4 = new javax.swing.JSpinner();
        gasto5 = new javax.swing.JSpinner();
        gasto6 = new javax.swing.JSpinner();
        gasto7 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        subtotalgastos = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        subtotaltotal = new javax.swing.JLabel();
        z = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        sobrofalto = new javax.swing.JLabel();
        zcometario = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(6, 18, 32));

        jPanel1.setBackground(new java.awt.Color(1, 96, 87));

        btnconfiguracion.setBackground(new java.awt.Color(102, 204, 255));
        btnconfiguracion.setForeground(new java.awt.Color(255, 255, 255));
        btnconfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/config.png"))); // NOI18N
        btnconfiguracion.setText("Configuración");
        btnconfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnconfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnconfiguracionMouseClicked(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/guardar.png"))); // NOI18N
        jLabel2.setText("Guardar");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/cheque.png"))); // NOI18N
        jLabel10.setText("Validar");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jfecha.setBackground(new java.awt.Color(1, 96, 87));
        jfecha.setForeground(new java.awt.Color(255, 255, 255));

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/cambio.png"))); // NOI18N
        jLabel28.setText("Cambiar Usuario");
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MiguelCastellanos\\Documents\\NetBeansProjects\\CorteCaja\\Resources\\img\\ticket.png")); // NOI18N
        jLabel1.setText("Boucher");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnconfiguracion)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnconfiguracion)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10)
                    .addComponent(jLabel28)
                    .addComponent(jLabel1)))
            .addComponent(jfecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("\"L\"1 :");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("\"L\" 2:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("\"L\"3 :");

        L1.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        L2.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        L3.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("MONEDA :");

        monedas.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("N. CHECHE :");

        cheques.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("SUBTOTAL:");

        subtotalL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        subtotalL.setForeground(new java.awt.Color(0, 0, 0));
        subtotalL.setText("$");

        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("BOUCHER:");

        boucher.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(l2comentario)
                                        .addGap(39, 39, 39))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(L1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                                .addComponent(L2))
                                            .addComponent(L3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(101, 101, 101)))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel29)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(l1comentario, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(subtotalL, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(14, 14, 14))))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(boucher, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                .addComponent(cheques, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(monedas, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addComponent(l3comentario, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(L1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)
                                .addComponent(monedas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l1comentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cheques, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(L2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)
                            .addComponent(boucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(l2comentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel16))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l3comentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(subtotalL)
                        .addContainerGap())))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jprovedor1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jPanel3.add(jprovedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 28, 330, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("PROVEDOR:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("MONTO:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, -1, -1));

        txtprovedor1.setForeground(new java.awt.Color(255, 0, 0));
        txtprovedor1.setText("$ 0.00");
        txtprovedor1.setEnabled(false);
        jPanel3.add(txtprovedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 130, -1));

        jprovedor2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   " }));
        jPanel3.add(jprovedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 68, 330, -1));

        jprovedor3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   " }));
        jPanel3.add(jprovedor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 108, 330, -1));

        jprovedor4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   " }));
        jPanel3.add(jprovedor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 148, 330, -1));

        jprovedor5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   " }));
        jPanel3.add(jprovedor5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 188, 330, -1));

        jprovedor6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "    " }));
        jPanel3.add(jprovedor6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 228, 330, -1));

        txtprovedor2.setForeground(new java.awt.Color(0, 0, 0));
        txtprovedor2.setText("$ 0.00");
        txtprovedor2.setEnabled(false);
        jPanel3.add(txtprovedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 130, -1));

        txtprovedor3.setForeground(new java.awt.Color(0, 0, 0));
        txtprovedor3.setText("$ 0.00");
        txtprovedor3.setEnabled(false);
        jPanel3.add(txtprovedor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 130, -1));

        txtprovedor4.setForeground(new java.awt.Color(0, 0, 0));
        txtprovedor4.setText("$ 0.00");
        txtprovedor4.setEnabled(false);
        jPanel3.add(txtprovedor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 130, -1));

        txtprovedor5.setForeground(new java.awt.Color(0, 0, 0));
        txtprovedor5.setText("$ 0.00");
        txtprovedor5.setEnabled(false);
        jPanel3.add(txtprovedor5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 130, -1));

        txtprovedor6.setForeground(new java.awt.Color(0, 0, 0));
        txtprovedor6.setText("$ 0.00");
        txtprovedor6.setEnabled(false);
        jPanel3.add(txtprovedor6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 130, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("SUBTOTA :");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        subtotalcompras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        subtotalcompras.setForeground(new java.awt.Color(0, 0, 0));
        subtotalcompras.setText("$");
        jPanel3.add(subtotalcompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 122, -1));

        por1.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        jPanel3.add(por1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 47, -1));

        jLabel21.setText("%");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        por2.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        jPanel3.add(por2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 48, -1));

        por3.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        jPanel3.add(por3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 47, -1));

        por4.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        jPanel3.add(por4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 47, -1));

        por5.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        jPanel3.add(por5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 47, -1));

        por6.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        jPanel3.add(por6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 47, -1));

        jLabel22.setText("%");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        jLabel23.setText("%");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        jLabel24.setText("%");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        jLabel25.setText("%");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, -1));

        jLabel26.setText("%");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("DESCRIPCIÓN :");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("IMPORTE :");

        gasto1.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        gasto2.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        gasto3.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        gasto4.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        gasto5.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        gasto6.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        gasto7.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("SUBTOTAL :");

        subtotalgastos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        subtotalgastos.setForeground(new java.awt.Color(0, 0, 0));
        subtotalgastos.setText("$");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(75, 75, 75))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtgasto1)
                        .addComponent(txtgasto2)
                        .addComponent(txtgasto3)
                        .addComponent(txtgasto4)
                        .addComponent(txtgasto5)
                        .addComponent(txtgasto6)
                        .addComponent(txtgasto7, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                    .addComponent(jLabel13))
                .addGap(64, 64, 64)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gasto1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(gasto2)
                    .addComponent(gasto3)
                    .addComponent(gasto4)
                    .addComponent(gasto5)
                    .addComponent(gasto6)
                    .addComponent(gasto7)
                    .addComponent(subtotalgastos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtgasto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gasto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtgasto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gasto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtgasto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gasto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtgasto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gasto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtgasto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gasto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtgasto6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gasto6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtgasto7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gasto7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(subtotalgastos))
                .addGap(22, 22, 22))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("COMPRAS PROVEDOR :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("GASTOS :");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("SUBTOTAL :");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Z :");

        subtotaltotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        subtotaltotal.setForeground(new java.awt.Color(0, 0, 0));
        subtotaltotal.setText("$");

        z.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        z.setForeground(new java.awt.Color(0, 0, 0));
        z.setText("$");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("SOBRO / FALTO");

        sobrofalto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sobrofalto.setForeground(new java.awt.Color(0, 0, 0));
        sobrofalto.setText("$");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("COMENTARIO:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel30)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(subtotaltotal, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(z, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(sobrofalto, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(zcometario, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtotaltotal)
                    .addComponent(jLabel19)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(z)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(sobrofalto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zcometario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addContainerGap())
        );

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("CAJA: ");

        txtusuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtusuario.setForeground(new java.awt.Color(255, 255, 255));
        txtusuario.setText("1");

        jLabel31.setText("V 2022.05.17");

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtusuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel31, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(246, 246, 246)))
                .addGap(13, 13, 13)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(258, 258, 258))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel9)
                .addGap(20, 20, 20)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel31)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnconfiguracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnconfiguracionMouseClicked

        ConfiguracionLogin cl = new ConfiguracionLogin();
        cl.setVisible(true);

    }//GEN-LAST:event_btnconfiguracionMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        String p1nombre = jprovedor1.getSelectedItem().toString();
        String p2nombre = jprovedor2.getSelectedItem().toString();
        String p3nombre = jprovedor3.getSelectedItem().toString();
        String p4nombre = jprovedor4.getSelectedItem().toString();
        String p5nombre = jprovedor5.getSelectedItem().toString();
        String p6nombre = jprovedor6.getSelectedItem().toString();
        String corte = z.getText();
        
        try {
            provedor.getReporte(getfecha(), users, (double)  L1.getValue(), (double)  L2.getValue(), (double)  L3.getValue(), (double) monedas.getValue(),
                    (double) cheques.getValue(), (double) boucher.getValue(), p1nombre, txtprovedor1.getText(),p2nombre, txtprovedor2.getText(),p3nombre,
                    txtprovedor3.getText(),p4nombre, txtprovedor4.getText(),p5nombre, txtprovedor5.getText(),p6nombre, txtprovedor6.getText(),subtotalcompras.getText(),
                    txtgasto1.getText(), (double) gasto1.getValue(), txtgasto2.getText(), (double) gasto2.getValue(), txtgasto3.getText(), (double) gasto3.getValue(), txtgasto4.getText(), (double) gasto4.getValue(),
                    txtgasto5.getText(), (double) gasto5.getValue(), txtgasto6.getText(), (double) gasto6.getValue(), txtgasto7.getText(), (double) gasto7.getValue(), subtotaltotal.getText(), corte, sobrofalto.getText()
                    , (double) por1.getValue(), (double) por2.getValue(), (double) por3.getValue(), (double) por4.getValue(), (double) por5.getValue(), (double) por6.getValue(), getTotalcompra(), getTotalGastos(), getUsuario(),
                    l1comentario.getText(), l2comentario.getText(), l3comentario.getText(), zcometario.getText());
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        try {
            switch(op){
                case "2":
                    llenarCampos();
                    break;
                case "4":
                    llenarCampos();
                    break;
                case "0":
                    llenarCampos();
                    break;
                default:
                    JOptionPane.showMessageDialog(rootPane, "Seleccione un usuario valido");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        op = JOptionPane.showInputDialog(rootPane, "Eliga un usuario: \n 4.-MAYOREO \n 2.-MENUDEO" );
        getUsuario();
        cc.leerArchivo();
        limpiarCampos();
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       Boucher boucher = new Boucher();
       boucher.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    double totalcompras;
    
    public void llenarCampos() throws SQLException{
        String DNI1, DNI2, DNI3, DNI4, DNI5, DNI6;
        double totalprovedor1, totalprovedor2, totalprovedor3, totalprovedor4, totalprovedor5, totalprovedor6;
        
            
            DNI1 = provedor.getIdProvedor(jprovedor1.getSelectedItem().toString());
            totalprovedor1 = provedor.getTotalCompraProvedor(DNI1, getfecha());
            System.out.println(provedor.getIdProvedor(jprovedor1.getSelectedItem().toString()));
            txtprovedor1.setText(formatoMoneda(totalprovedor1)+"");

            DNI2 = provedor.getIdProvedor(jprovedor2.getSelectedItem().toString());
            totalprovedor2 = provedor.getTotalCompraProvedor(DNI2, getfecha());
            txtprovedor2.setText(formatoMoneda(totalprovedor2)+"");
            
            DNI3 = provedor.getIdProvedor(jprovedor3.getSelectedItem().toString());
            totalprovedor3 = provedor.getTotalCompraProvedor(DNI3, getfecha());
            txtprovedor3.setText(formatoMoneda(totalprovedor3)+"");
            
            DNI4 = provedor.getIdProvedor(jprovedor4.getSelectedItem().toString());
            totalprovedor4 = provedor.getTotalCompraProvedor(DNI4, getfecha());
            txtprovedor4.setText(formatoMoneda(totalprovedor4)+"");
            
            DNI5 = provedor.getIdProvedor(jprovedor5.getSelectedItem().toString());
            totalprovedor5 = provedor.getTotalCompraProvedor(DNI5, getfecha());
            txtprovedor5.setText(formatoMoneda(totalprovedor5)+"");
            
            DNI6 = provedor.getIdProvedor(jprovedor6.getSelectedItem().toString());
            totalprovedor6 = provedor.getTotalCompraProvedor(DNI6, getfecha());
            txtprovedor6.setText(formatoMoneda(totalprovedor6)+"");
            
            totalcompras = totalprovedor1 + totalprovedor2 + totalprovedor3 + totalprovedor4 + totalprovedor5 + totalprovedor6;
            subtotalcompras.setText(formatoMoneda(totalcompras)+"");

            subtotalgastos.setText(formatoMoneda(getTotalGastos())+"");
            
            subtotalL.setText(formatoMoneda(getTotalL())+"");
            
            double total1 = getTotalL() + getTotalGastos() + totalcompras;
            
            subtotaltotal.setText(formatoMoneda(total1)+"");
            
            z.setText(formatoMoneda((double) provedor.getZ(getfecha(),op))+"");
            
            double fs = total1 - (double) provedor.getZ(getfecha(),op);
            
            sobrofalto.setText(formatoMoneda(fs)+"");
            
            
            JOptionPane.showMessageDialog(rootPane, "Datos cargado con exito... "
                    + "Verifica que los datos sean corretos antes de guardar...");
    }
    
    
    public double getTotalL(){
        double totalL = 0;
        totalL = (double) L1.getValue() + (double) L2.getValue() + (double) L3.getValue() + (double) monedas.getValue() + (double) cheques.getValue() + (double) boucher.getValue();
        return totalL;
    }
    
    public double getTotalcompra(){
        return totalcompras;
    }
    
    public String formatoMoneda(double Format){   
        Locale usa = new Locale("en", "US");
        Currency dollars = Currency.getInstance(usa);
        NumberFormat dollarFormat = NumberFormat.getCurrencyInstance(usa);
        return dollarFormat.format(Format);
    }
    
    public String getfecha(){
        String fecha;
        Calendar cal = jfecha.getCalendar();
        int datevar = cal.get(Calendar.DATE);
        int monthvar = cal.get(Calendar.MONTH);
        int yearvar = cal.get(Calendar.YEAR);
        monthvar = monthvar+1;
        fecha = datevar+"."+monthvar+"."+yearvar;
        return fecha;
    }
    
    
    public void getProvedores() throws SQLException{
        int indexOf = provedor.cargarProvedores().size();
        System.out.println(indexOf);
        for (int i = 0; i < indexOf; i++){
            jprovedor1.addItem(provedor.cargarProvedores().get(i).getNombre());
            jprovedor2.addItem(provedor.cargarProvedores().get(i).getNombre());
            jprovedor3.addItem(provedor.cargarProvedores().get(i).getNombre());
            jprovedor4.addItem(provedor.cargarProvedores().get(i).getNombre());
            jprovedor5.addItem(provedor.cargarProvedores().get(i).getNombre());
            jprovedor6.addItem(provedor.cargarProvedores().get(i).getNombre());
        }
    }
    
    double totalgasto;
    
    public double getTotalGastos(){
        totalgasto = (double) gasto1.getValue() + (double) gasto2.getValue() + (double) gasto3.getValue() + (double) gasto4.getValue() + (double) gasto5.getValue() + (double) gasto6.getValue() + (double) gasto7.getValue();
        return totalgasto;
    }
    
    public String getUsuario(){
        switch (op){
            case "2":
                users = "MENUDEO";
                break;
            case "4":
                users = "MAYOREO";
                break;
            default:
                users = "ADMINISTRADOR";
                op = "0";
                JOptionPane.showMessageDialog(rootPane, "Usuario Administrador");
        }
        txtusuario.setText(users);
        return users;
    }
    
    public void limpiarCampos(){
        totalgasto = 0;
        L1.setValue(0.0);
        L2.setValue(0.0);
        L3.setValue(0.0);
        l1comentario.setText("");
        l2comentario.setText("");
        l3comentario.setText("");
        monedas.setValue(0.0);
        cheques.setValue(0.0);
        boucher.setValue(0.0);
        subtotalL.setText("");
        jprovedor1.setSelectedIndex(0);
        jprovedor2.setSelectedIndex(0);
        jprovedor3.setSelectedIndex(0);
        jprovedor4.setSelectedIndex(0);
        jprovedor5.setSelectedIndex(0);
        jprovedor6.setSelectedIndex(0);
        por1.setValue(0.0);
        por2.setValue(0.0);
        por3.setValue(0.0);
        por4.setValue(0.0);
        por5.setValue(0.0);
        por6.setValue(0.0);
        txtprovedor1.setText("$0.00");
        txtprovedor2.setText("$0.00");
        txtprovedor3.setText("$0.00");
        txtprovedor4.setText("$0.00");
        txtprovedor5.setText("$0.00");
        txtprovedor6.setText("$0.00");
        subtotalcompras.setText("$0.00");
        txtgasto1.setText("");
        txtgasto2.setText("");
        txtgasto3.setText("");
        txtgasto4.setText("");
        txtgasto5.setText("");
        txtgasto6.setText("");
        txtgasto7.setText("");
        gasto1.setValue(0.0);
        gasto2.setValue(0.0);
        gasto3.setValue(0.0);
        gasto4.setValue(0.0);
        gasto5.setValue(0.0);
        gasto6.setValue(0.0);
        gasto7.setValue(0.0);
        subtotalgastos.setText("");
        subtotaltotal.setText("");
        z.setText("");
        sobrofalto.setText("");
        zcometario.setText("");
    
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Home().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner L1;
    private javax.swing.JSpinner L2;
    private javax.swing.JSpinner L3;
    private javax.swing.JSpinner boucher;
    private javax.swing.JLabel btnconfiguracion;
    private javax.swing.JSpinner cheques;
    private javax.swing.JSpinner gasto1;
    private javax.swing.JSpinner gasto2;
    private javax.swing.JSpinner gasto3;
    private javax.swing.JSpinner gasto4;
    private javax.swing.JSpinner gasto5;
    private javax.swing.JSpinner gasto6;
    private javax.swing.JSpinner gasto7;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private com.toedter.calendar.JDateChooser jfecha;
    private javax.swing.JComboBox<String> jprovedor1;
    private javax.swing.JComboBox<String> jprovedor2;
    private javax.swing.JComboBox<String> jprovedor3;
    private javax.swing.JComboBox<String> jprovedor4;
    private javax.swing.JComboBox<String> jprovedor5;
    private javax.swing.JComboBox<String> jprovedor6;
    private javax.swing.JTextField l1comentario;
    private javax.swing.JTextField l2comentario;
    private javax.swing.JTextField l3comentario;
    private javax.swing.JSpinner monedas;
    private javax.swing.JSpinner por1;
    private javax.swing.JSpinner por2;
    private javax.swing.JSpinner por3;
    private javax.swing.JSpinner por4;
    private javax.swing.JSpinner por5;
    private javax.swing.JSpinner por6;
    private javax.swing.JLabel sobrofalto;
    private javax.swing.JLabel subtotalL;
    private javax.swing.JLabel subtotalcompras;
    private javax.swing.JLabel subtotalgastos;
    private javax.swing.JLabel subtotaltotal;
    private javax.swing.JTextField txtgasto1;
    private javax.swing.JTextField txtgasto2;
    private javax.swing.JTextField txtgasto3;
    private javax.swing.JTextField txtgasto4;
    private javax.swing.JTextField txtgasto5;
    private javax.swing.JTextField txtgasto6;
    private javax.swing.JTextField txtgasto7;
    private javax.swing.JTextField txtprovedor1;
    private javax.swing.JTextField txtprovedor2;
    private javax.swing.JTextField txtprovedor3;
    private javax.swing.JTextField txtprovedor4;
    private javax.swing.JTextField txtprovedor5;
    private javax.swing.JTextField txtprovedor6;
    private javax.swing.JLabel txtusuario;
    private javax.swing.JLabel z;
    private javax.swing.JTextField zcometario;
    // End of variables declaration//GEN-END:variables
}
